version: "3.4"
networks:
  nexus:
services:
  nginx:
    image: nginx:1.19.2-alpine
    restart: always
    networks:
      - nexus
    ports:
      - 443:443
      - 80:80
    volumes:
      - /data/certs:/etc/nginx/certs/
      - /data/config:/etc/nginx/conf.d/
  nexus:
    image: sonatype/nexus3:3.27.0
    restart: always
    networks:
      - nexus
    volumes:
      - nexus-data:/nexus-data
    expose:
      - "8081"
volumes:
  nexus-data:
